version: '3'

services:
  app:
    build: ../../

  nginx:
    image: nginx:1.13.0
    links:
      - app:app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d
    command: ['nginx', '-g', 'daemon off;']
    ports:
      - 80:80